### PR TITLE
ENH: remove builds on push, run on pull only if specific workflow modified, do not gunzip .deb - fixed in actions

### PR DESCRIPTION
**Pull request by yarikoptic**

### CODE REVIEW

**Comment by yarikoptic** [comment]
ok, git-annex workflow failures seems possibly legit (i.e. introduced by recent git-annex and/or git), have a peek please @kyleam: (below is from `maint` branch run)
```
2020-04-14T13:58:30.5683885Z datalad.tests.test_version.test__version__ ... SKIP: no /opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/datalad/tests/../../CHANGELOG.md found
2020-04-14T13:58:30.5685258Z /tmp/datalad_temp_tree_test_paths_with_forward_slashes946hbrx7
2020-04-14T13:58:30.5686972Z 
2020-04-14T13:58:30.5688940Z Versions: appdirs=1.4.3 boto=2.49.0 cmd:7z=16.02 cmd:annex=8.20200330+git72-gba6f46c11-1~ndall+1 cmd:bundled-git=2.24.0 cmd:git=2.24.0 cmd:system-git=2.26.0 cmd:system-ssh=7.6p1 git=3.1.1 gitdb=4.0.4 humanize=2.3.0 iso8601=0.1.12 keyring=21.2.0 keyrings.alt=3.4.0 msgpack=1.0.0 patoolib=1.12 requests=2.23.0 tqdm=4.45.0 wrapt=1.12.1
2020-04-14T13:58:30.5692634Z ======================================================================
2020-04-14T13:58:30.5694403Z Obscure filename: str=b' "\';a&b&c\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 `| ' repr=' "\';a&b&cÎ”Ð™×§Ù…à¹—ã‚ `| '
2020-04-14T13:58:30.5697152Z FAIL: datalad.plugin.tests.test_addurls.TestAddurls.test_addurls
2020-04-14T13:58:30.5698442Z Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
2020-04-14T13:58:30.5700947Z ----------------------------------------------------------------------
2020-04-14T13:58:30.5702558Z Environment: LANG='C' PATH='/opt/hostedtoolcache/Python/3.7.6/x64/bin:/opt/hostedtoolcache/Python/3.7.6/x64:/usr/share/rust/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/runner/.dotnet/tools:/home/runner/.config/composer/vendor/bin' LC_CTYPE='C.UTF-8' GIT_PYTHON_GIT_EXECUTABLE='/usr/lib/git-annex.linux/git'
2020-04-14T13:58:30.5703992Z Traceback (most recent call last):
2020-04-14T13:58:30.5705580Z   File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
2020-04-14T13:58:30.5707206Z     self.test(*self.arg)
2020-04-14T13:58:30.5708908Z   File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 732, in newfunc
2020-04-14T13:58:30.5710380Z     return t(*(arg + (filename,)), **kw)
2020-04-14T13:58:30.5712317Z   File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/datalad/plugin/tests/test_addurls.py", line 438, in test_addurls
2020-04-14T13:58:30.5713597Z     eq_(n_annex_commits + 2, get_annex_commit_counts())
2020-04-14T13:58:30.5714476Z AssertionError: 4 != 6
2020-04-14T13:58:30.5714928Z 
2020-04-14T13:58:30.5716890Z ======================================================================
2020-04-14T13:58:30.5718115Z FAIL: datalad.support.tests.test_annexrepo.test_AnnexRepo_always_commit
2020-04-14T13:58:30.5719603Z ----------------------------------------------------------------------
2020-04-14T13:58:30.5720904Z Traceback (most recent call last):
2020-04-14T13:58:30.5722285Z   File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
2020-04-14T13:58:30.5723302Z     self.test(*self.arg)
2020-04-14T13:58:30.5724762Z   File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 732, in newfunc
2020-04-14T13:58:30.5731418Z     return t(*(arg + (filename,)), **kw)
2020-04-14T13:58:30.5737524Z   File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/datalad/support/tests/test_annexrepo.py", line 728, in test_AnnexRepo_always_commit
2020-04-14T13:58:30.5738707Z     eq_(len(out_list), 2, "Output:\n%s" % out_list)
2020-04-14T13:58:30.5739557Z AssertionError: Output:
2020-04-14T13:58:30.5741377Z ['(recording state in git...)', '+ Tue, 14 Apr 2020 13:45:41 UTC  "\';a&b&cÎ”Ð™×§Ù…à¹—ã‚ `| _1 | 01d00ad2-60b3-4013-90bd-202fe3e4aadb -- runner@fv-az92:/tmp/datalad_temp_test_AnnexRepo_always_commitfe1rmnt0', '+ Tue, 14 Apr 2020 13:45:42 UTC  "\';a&b&cÎ”Ð™×§Ù…à¹—ã‚ `| _2 | 01d00ad2-60b3-4013-90bd-202fe3e4aadb -- runner@fv-az92:/tmp/datalad_temp_test_AnnexRepo_always_commitfe1rmnt0']
2020-04-14T13:58:30.5742285Z 
2020-04-14T13:58:30.5743188Z ----------------------------------------------------------------------
2020-04-14T13:58:30.5743963Z Ran 1097 tests in 3165.289s
2020-04-14T13:58:30.5744287Z 
2020-04-14T13:58:30.5744886Z FAILED (SKIP=119, failures=2)
2020-04-14T13:58:30.6739326Z ##[error]Process completed with exit code 1.
2020-04-14T13:58:30.6762314Z Cleaning up orphan processe
```

**Comment by kyleam** [comment]
> have a peek please @kyleam:

Will do.  Thanks for pinging.

**Comment by kyleam** [comment]
Bisected the `test_AnnexRepo_always_commit` failure to git-annex's eedd73b84 (fix reversion caused by earlier optimisation to git-annex branch reads, 2020-04-10).  I'll take a closer look to see whether that result makes sense and think about where an adjustment should be made.

**Comment by yarikoptic** [comment]
THANK YOU @kyleam.  So it is the state of things that it does fail, merging this minor RFing, hopefully would come useful ;)

**Comment by kyleam** [comment]
[Filed][0] on git-annex's end.  I think we might need some tweaks on our end still, but let's see what comes of that.

[0]: https://git-annex.branchable.com/bugs/commits_created_despite_alwayscommit__61__false_as_of_recent_change/

**Comment by yarikoptic** [comment]
Perfect, thank you!!

**Pull request merged**
