### PR TITLE
Add testing against release of datalad-next

### PR DESCRIPTION
**Pull request by yarikoptic**
ATM added testing only against release of next and only against datalad-maint.  WDYT @mih -- should I change to test against `master` version of datalad-next?

TODOs
- [ ] add to the README.md table

### CODE REVIEW

**Comment by yarikoptic** [comment]
and do I need to do anything to make datalad-next patch things up?  might relate to the following PR I am yet to get back to:
- https://github.com/datalad/datalad/pull/7597

**Comment by yarikoptic** [comment]
not sure why CI didn't run at all. anyways should probably refactor to not have 2x2 with different annex installation methods.

**Comment by mih** [comment]
Testing against a release is sufficient.

The get full impact it needs:

```
git config --global --add datalad.extensions.load next
```

**Comment by yarikoptic** [comment]
nice ! crawler and xnat are chronically red ATM, the others stay green.
but I think I forgot that for the badge we need pretty much a separate workflow , not just a matrix run, so I will have to redo at that level :-/  later...

**Pull request merged**
