### PR TITLE
Add tests from build-git-annex.yaml to build-git-annex-windows.yaml

### LINKED ISSUE #49: add testing of datalad for windows
not all tests are "windows friendly" yet but we have a good number of them running in datalad via appveyor.  We should replicate (and may be eventually extend) that list of them here while testing upon successful build of datalad.

### PR DESCRIPTION
**Pull request by jwodder**
Closes #49.

### CODE REVIEW

**Comment by jwodder** [comment]
@yarikoptic
* Is there a way to port the nfs-tmp test setup to Windows, so should I not even bother?
* For the "Seek of dynlibs"/strace test under test-annex-more, I simply changed `libpcre.*so` to `libpcre.*dll`.  Is that correct?

**Comment by yarikoptic** [comment]
nfs -- yeah, please do not even try to bother!!!

strace -- also do not bother I think.  This is not a "standalone" bundle, there should be no shimming, I do not think we would succeed with stracing.

**Comment by yarikoptic** [comment]
datalad special remote and git-annex stalling was addressed today in [8.20201007-144-g7245a9ed5](https://git.kitenet.net/index.cgi/git-annex.git/commit/?id=7245a9ed533c87abb70b2b9d06a5d3d5ea2f23b4) , I have restarted the tests -- they better do not stall! (they might / likely to fail still)

**Comment by yarikoptic** [comment]
@jwodder please rebase the pr  so we account for all recent changes

**Comment by jwodder** [comment]
@yarikoptic Rebased.

**Comment by yarikoptic** [comment]
Even if testing against datalad would fail ATM (which I think it would) I am ok to have it merged for the purpose of easier #67, and deal with failing tests later in that repo.

**Comment by yarikoptic** [comment]
I think those tests just hanged -- it had been over 2h and there is no output produced.  We will need to figure it out, but for now - just merge, and comment out with `#TODO` or alike running the tests - we will get back to them later

**Comment by yarikoptic** [comment]
actually I will just do it quickly

**Comment by yarikoptic** [comment]
oh, I just spotted seems missing `"` in
```
      - name: install ${{ matrix.version }} datalad
        run: |
          if [ "${{ matrix.version }}" = "release" ]; then
            # Authorize so that we don't run up against low API rate limits
            commitish="$(curl -fsSL -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/datalad/datalad/releases/latest | jq -r .tag_name)"
```
will fix too

**Comment by yarikoptic** [comment]
grr,,, I should stop rushing, nothing is missing per se -  but not sure if nested `""` would be always processed properly...

**Pull request merged**
