### PR TITLE
Add the ukbiobank extension

### PR DESCRIPTION
**Pull request by mih**
I assume that it will fail due to the missing `[devel]` install target. I do not yet know how to add such to `setup.cfg`.

Maybe like this?

```
[options.extras_require]
devel = 
```

But it doesn't seem to be needed. Do I guess this just needs to wait for the 0.3 release.

### CODE REVIEW

**Comment by yarikoptic** [comment]
Yeap, complete unrelated example is in https://github.com/dandi/dandi-cli/blob/master/setup.cfg#L62

**Comment by yarikoptic** [comment]
Alternative (to avoid release) is to add another option into schema Wich would default to level but could be empty or something else, and adjust template at https://github.com/datalad/datalad-extensions/blob/master/templates/.github/workflows/test-%7B%7Bextension.name%7D%7D.yaml#L48

**Comment by yarikoptic** [comment]
Note: no tests were ran

```
datalad_ukbiobank tests0s
OK
Run mkdir -p __testhome__
nose.plugins.cover: ERROR: Coverage not available: unable to import coverage module

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```
that is why it is green

**Comment by mih** [comment]
So do you want to have this PR remain open till tests are executed here? I assume that would need an extension release, because ukbiobank master already has tests with almost complete coverage now.

**Comment by yarikoptic** [comment]
ok, since 0.3 was released, I will kick the workflow to be reran - hopefully it would pick up the tests.

**Comment by yarikoptic** [comment]
woohoo -- it runs the tests and they pass!

**Comment by mih** [comment]
Great! Thx!

**Pull request merged**
