### PR TITLE
[WIP] Fix hirni test run

### PR DESCRIPTION
**Pull request by bpoldrack**
Note, that this will fully succeed only with a new hirni release. I'm justing putting up all the pieces.
Therefore depends on https://github.com/psychoinformatics-de/datalad-hirni/pull/160 being merged and released before this PR can take effect.

### CODE REVIEW

**Comment by bpoldrack** [comment]
@yarikoptic : Have a look at the diff please. I'm not clear whether we want to go with that kind of commit, since those workflows are supposed to be generated, right? So - what do we do about this kind of change? Enhancing the generation to be that flexible seems like a lot of effort to do (and properly test) for one usecase we have so far.

Also: Why doesn't a PR *here* trigger the actual workflows anymore? Don't think that makes sense.

**Comment by bpoldrack** [comment]
> The purpose for the test run here is to test released versions of extensions against master branch of datalad, as the title for that column says: "CI: Released + DL master". Each extension is supposedly tests its master against released version of datalad, so column says: "CI: master + DL Release" and we link to that extension's travis report.
datalad master itself tests against (some) master of extensions to make sure it is all compatible while in development stage (I believe we do not include those reports here)

Yes, I'm aware of that. I think you misunderstood my question. The point is that I changed the workflow file directly as opposed to introducing big changes to the generation of those files, allowing to specify such a change in the test setup in `extensions.yml` instead.

**Comment by yarikoptic** [comment]
is `hirni-toolbox` needed to get testing done? 
then it should be either
- a. installed by tests fixture (global or more specific to the tests module needing it) - that would allow to avoid any tuning/hardcoding of any CI or other (package build time) tests setup.  If you were using `pytest` it could have been along this example:
https://github.com/ReproNim/reproman/blob/HEAD/reproman/distributions/tests/test_venv.py#L34 or one of other fun ones in https://github.com/ReproNim/reproman/blob/57be5672e8451026d8c149e3a2ef40044eca2fb5/reproman/tests/fixtures.py .  BUT it should probably make it persistent for local testing convenience -- so similar to those "docker" fixtures just rely  that `datalad install` (or clone?) would be ok  to be reran if repository is already there (somewhere in user's cache) and just make sure that it fulfills desired "state" (commit)... which also suggests 
- b. that may be you would want that dataset to be a submodule?  then we could adjust the generator so it would do `git submodule init` before testing.

In `a.` -- Note that it would also be nice to be able to "enable" or "disable" via e.g. env var or may be an option to the tests runner. For that (env or options to test runner) - we indeed would need to tune up the generator.  I guess the most logical is to add `tester_args` and `tester_env` section with whatever env vars to set.  Indeed - it is a bit more work, but IMHO would be 10x more useful in the longer run as other extensions would need something like that setup.

In `b.` - I guess corresponding tests could just skip if they detect submodule content not being provided.

So -- for the fastest/quick&dirty solution `b.` is the easiest imho.

BTW in https://github.com/psychoinformatics-de/datalad-hirni/blob/master/setup.py#L55 I do not see `[devel]` setup_requires - might want to add it?

**Comment by yarikoptic** [comment]
Just FTR, toolbox is also available from http://datasets.datalad.org/?dir=/psychoinformatics-de/hirni-toolbox now, so we could eliminate the possible cause of data hosting portal if that dataset is added as `type=git` special remote. See https://github.com/datalad/datalad/issues/4697 for "instructions"

**Comment by bpoldrack** [comment]
Closing in favor of PR #39

**Pull request closed without merging**
