### PR TITLE
Update README to refer to AppVeyor instead of Travis

### PR DESCRIPTION
**Pull request by bpoldrack**
Overview referred to last Travis build for datalad-hirni, but Travis is no longer used. Therefore referenced "master+ DL released" build was outdated. Same is true for datalad-ukbiobank.

### CODE REVIEW

**Comment by bpoldrack** [comment]
Note, that datalad-neuroimaging is about to switch, too: https://github.com/datalad/datalad-neuroimaging/pull/87. Same changes need to be applied whenever that PR is merged.

**Review by yarikoptic — CHANGES_REQUESTED** [review]
reminder -- README.md is populated by the script.  So tune up needs to be done to the spec and to the script -- most likely to instruct in the spec where to look for the badge if not on travis

**Comment by bpoldrack** [comment]
> reminder -- README.md is populated by the script. So tune up needs to be done to the spec and to the script -- most likely to instruct in the spec where to look for the badge if not on travis

True. Forgot about that.

**Comment by bpoldrack** [comment]
Adapted, @yarikoptic. Fine with that approach?

**Comment by yarikoptic** [comment]
Looks great to me, thank you!

**Pull request merged**
