### PR TITLE
download-latest-artifact: Remove `--silent` from curl to see what happens

### PR DESCRIPTION
**Pull request by jwodder**
Part of #74.  Merge and check the logs later after the workflows run.

### CODE REVIEW

**Comment by yarikoptic** [comment]
need to `touch` OSX workflow to trigger it

**Comment by jwodder** [comment]
@yarikoptic Did you mean to comment on this issue?  datalad-extensions doesn't have an OSX workflow.

**Comment by yarikoptic** [comment]
wanted to comment here, but not about OSX (indeed mixed up in that) ;) workflows need to be touched to trigger a rerun of workflows to check this change

**Comment by jwodder** [comment]
@yarikoptic Just touching them won't cause any changes to be committed; the file contents need to actually be changed.

**Comment by yarikoptic** [comment]
yeap, that is what I meant

**Comment by jwodder** [comment]
Mystery solved; see #77.

**Pull request closed without merging**
